[FIX] Securing math operations from overflows
aave-starknet-project/aave-starknet-core pull request #131
Opened 2022-09-05 06:05 UTC by kaliberpoziomka

This PR should secure math operations from overflows.

2022-09-05 09:45 UTC, achab approved these changes
Thanks for this effort! I reviewed variable names and it looks OK!

2022-09-06 07:59 UTC, hsouf commented on contracts/protocol/libraries/math/math_utils.cairo
> +        let (temp_result, mul_overflow) = uint256_mul(rate, time_delta)
why not use `mul` on `SafeUint256` instead? it performs exactly the same checks.

2022-09-06 07:59 UTC, hsouf commented on contracts/protocol/libraries/math/math_utils.cairo
> +            assert mul_overflow = Uint256(0, 0)
`mul_overflow`->`overflow`

2022-09-06 07:59 UTC, hsouf commented on contracts/protocol/libraries/math/math_utils.cairo
> +        let (interest, add_overflow) = uint256_add(Uint256(WadRayMath.RAY, 0), result)
same here

2022-09-06 08:01 UTC, hsouf commented on contracts/protocol/libraries/math/math_utils.cairo
> +        let (temp_result, mul_overflow) = uint256_mul(rate, time_delta)
let's remove the op tag`mul_overflow`->`overflow`

2022-09-06 08:04 UTC, hsouf commented on contracts/protocol/libraries/math/math_utils.cairo
> +        let (period_square, mul_overflow_1) = uint256_mul(
using SafeUint256 will save you from the hassle of coming up with different names for overflows on the same file

2022-09-06 08:10 UTC, hsouf requested changes
Thank you @kaliberpoziomka for this PR. I suggest we use the SafeUint256 library or implement our own to use it on the rest of the code.

2022-09-07 08:35 UTC, kaliberpoziomka commented on contracts/protocol/libraries/math/math_utils.cairo
> +        let (period_square, mul_overflow_1) = uint256_mul(
Yes, I agree with all the comments

2022-09-07 08:43 UTC, achab commented on contracts/protocol/libraries/math/math_utils.cairo
> +%lang starknet
why is this line needed now?

2022-09-07 08:44 UTC, achab commented on contracts/protocol/libraries/math/percentage_math.cairo
> +        let (value_mul_percentage, mul_overflow) = uint256_mul(value, percentage)
we should also use `SafeUint256.mul` here, right?

2022-09-07 08:49 UTC, kaliberpoziomka commented on contracts/protocol/libraries/math/math_utils.cairo
> +%lang starknet
when importing file with this %lang specification we need to specify it too. OZ SafeUint256 got this, so I needed to add this as well

2022-09-07 08:56 UTC, kaliberpoziomka commented on contracts/protocol/libraries/math/percentage_math.cairo
> +        let (value_mul_percentage, mul_overflow) = uint256_mul(value, percentage)
yes, thank you

2022-09-07 08:57 UTC, achab commented on contracts/protocol/libraries/math/math_utils.cairo
> +%lang starknet
oh ok got it! thanks

2022-09-10 14:10 UTC, hsouf approved these changes

2022-09-21 06:27 UTC, achab commented on tests/unit_tests/protocol/libraries/math/test_percentage_math.cairo
> +from starkware.cairo.common.cairo_builtins import HashBuiltin
why this? the test didn't pass?

2022-09-21 10:52 UTC, merged