Added configurator logic library
aave-starknet-project/aave-starknet-core pull request #63
Opened 2022-08-03 08:13 UTC by achab

2022-08-03 10:12 UTC, msaug commented on contracts/protocol/libraries/types/data_types.cairo
>      struct ReserveConfigurationMap:
Now that I think of it, `ReserveConfigurationMap` might not be the best name possible since it's not a bitmap but just a regular struct.

2022-08-04 09:25 UTC, hsouf commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +        let (contract_address) = get_contract_address()
can we use `proxy_admin` here instead of `contract_address` for more readability 🥇

2022-08-04 09:31 UTC, hsouf commented on contracts/protocol/libraries/aave_upgradeability/initializable_immutable_admin_upgradeability_proxy.cairo
> +            function_selector=INITIALIZE_SELECTOR,
Our proxy should stay generic, what if in the future we needed to use the proxy to initialize an implementation with a different selector? other than initialize?

2022-08-04 09:34 UTC, hsouf requested changes
Thank you @achab for this PR! I think the proxy should keep taking the selector as param on `initialize()` the same way  `upgarde_to_and_call()` does.

2022-08-04 09:55 UTC, achab commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +        let (contract_address) = get_contract_address()
agree! I don't like vague terms neither, thanks for pointing that

2022-08-04 09:56 UTC, achab commented on contracts/protocol/libraries/aave_upgradeability/initializable_immutable_admin_upgradeability_proxy.cairo
> +            function_selector=INITIALIZE_SELECTOR,
agreed as well, I've done that to refactor but thought about this problem. will revert

2022-08-23 09:31 UTC, hsouf commented on tests/test_suites/with_deployment/test_runs.cairo
> +        dai,
nice catch

2022-08-23 09:37 UTC, hsouf commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +        # TODO: update this once we implement interest rate strategy
interest rate strategy was added to the codebase, you can rebase from main. It should be safe to emit `input.interest_rate_strategy_address` instead of `0`

2022-08-23 09:41 UTC, hsouf approved these changes

2022-08-23 10:43 UTC, achab commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +        # TODO: update this once we implement interest rate strategy
not sure it has been added, the PR is still open: https://github.com/aave-starknet-project/aave-starknet-core/pull/99

2022-08-23 14:41 UTC, msaug approved these changes
Ready to go ! Just a small comment regarding the incentives controller in AToken, but I think a lot of things need to be changed so it's not a big deal.

2022-08-23 14:41 UTC, msaug commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +            cast(new (pool, input.treasury, input.underlying_asset, input.incentives_controller, input.underlying_asset_decimals, input.a_token_name, input.a_token_symbol), felt*),
is this cast necessary ? Isn't new already returning a pointer to a felt?

2022-08-23 14:41 UTC, msaug commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +    func _init_token_with_proxy{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}(
internal function could be outside the namespace

2022-08-23 14:41 UTC, msaug commented on contracts/protocol/libraries/logic/pool_logic.cairo
> +            &reserve, DataTypes.ReserveData.SIZE, &params.reserves_count, DataTypes.ReserveData.id
Didn't think of accessing indexes like this, nice one 👍

2022-08-23 14:41 UTC, msaug commented on contracts/protocol/libraries/logic/validation_logic.cairo
> +        let (asset) = IAToken.UNDERLYING_ASSET_ADDRESS(reserve.a_token_address)
I'm in favor of adding a new member `underlying_asset` in `DataTypes.ReserveData`instead of having to query AToken for the underlying asset. Especially since the `ReserveConfiguration` indexing is done by asset (which is not the case in solidity). Maybe for another PR

2022-08-23 14:41 UTC, msaug commented on contracts/protocol/tokenization/a_token_library.cairo
> +        let (controller) = _incentives_controller.read()
`incentives_controller` should come from `IncentivizedERC20_incentives_controller`

2022-08-23 15:16 UTC, EdgarBarrantes approved these changes
Other than a small nitpick regarding constants: :shipit:

2022-08-23 15:16 UTC, EdgarBarrantes commented on contracts/protocol/tokenization/a_token_library.cairo
> +        let (controller) = _incentives_controller.read()
Correct, but would merge as is, I can take over otherwise it'd overlap wtih me deleting that storage variable in my branch.

2022-08-23 15:16 UTC, EdgarBarrantes commented on tests/unit_tests/protocol/libraries/logic/test_configurator_logic.cairo
> +const MOCK_ACL_MANAGER = 101
There are some constants available that you could use in the [constants file](https://github.com/aave-starknet-project/aave-starknet-core/blob/main/tests/utils/constants.cairo#L15).

2022-08-23 15:28 UTC, achab commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +            cast(new (pool, input.treasury, input.underlying_asset, input.incentives_controller, input.underlying_asset_decimals, input.a_token_name, input.a_token_symbol), felt*),
good point, I always use this cast but it might now be necessary

2022-08-23 15:54 UTC, achab commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +    func _init_token_with_proxy{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}(
OZ has updated their recommendation: both internal and "external" (i.e. to be exposed by the contract) should be under the namespace. See https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/pages/extensibility.adoc#libraries

2022-08-23 16:48 UTC, msaug commented on contracts/protocol/libraries/logic/configurator_logic.cairo
> +    func _init_token_with_proxy{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}(
hm, I said internal but actually, they call it `private`
> private: private to a library, not meant to be used outside the module or imported

And they implement these outside the namespace

2022-08-23 18:15 UTC, achab commented on contracts/protocol/libraries/logic/validation_logic.cairo
> +        let (asset) = IAToken.UNDERLYING_ASSET_ADDRESS(reserve.a_token_address)
Agree, I'm not proud of this additional call. It's not easy to replicate the usage of solidity library, adding a member is a good option. I've just created an issue (#112) to tackle this.

2022-08-25 08:16 UTC, merged